export const language = 'sv' as const
export const locale = 'sv-SE' as const

export const copy = {
  metadata: {
    title: 'Smart Home Kiosk',
    description: 'En kontrollpanel för smarta hem.',
    applicationName: 'Smart Home Kiosk',
    homeScreenTitle: 'Hemkontroll',
  },
  dashboard: {
    title: 'Hemöversikt',
    layout: 'Layout',
    chooseLayout: 'Välj dashboardlayout',
    layouts: {
      pages: 'Sidor',
      apps: 'Appar',
      tabs: 'Flikar',
      expandable: 'Expanderbara paneler',
      widgets: 'Widgetar',
    },
    travel: 'Resor',
    departures: 'Kollektivtrafik',
    transit: 'Kollektivtrafik',
    smartHome: 'Smart Home',
    moreSpace: 'Utrymme för mer',
    emptyHome: 'Startsidan saknar innehåll och du skickas vidare till översikten.',
  },
  refresh: {
    auto: 'Auto',
    updateControls: 'Uppdateringskontroller för {label}',
    fetchAutomatically: 'Hämta {label} automatiskt',
    retry: 'Försök igen: {label}',
    updating: 'Uppdaterar {label}',
  },
  printer: {
    eyebrow: 'Verkstad',
    title: '3D-skrivare',
    label: 'skrivare',
    refresh: 'Uppdatera skrivarstatus',
    loading: 'Hämtar skrivarstatus…',
    loadError: 'Det gick inte att hämta skrivarstatus.',
    disconnected: 'Frånkopplad',
    disconnectedHelp: 'Skrivaren är frånkopplad. Kontrollera anslutningen till OctoPrint.',
    activeJob: 'Pågående jobb',
    progress: 'Förlopp',
    progressAria: 'Utskriftsförlopp',
    remaining: 'Cirka {duration} återstår',
    minutesAndSeconds: '{minutes} min {seconds} s',
    seconds: '{seconds} s',
    ready: 'Redo för utskrift',
    progressUnavailable: 'Förloppet är inte tillgängligt för det här jobbet.',
    noActivePrint: 'Ingen aktiv utskrift',
    confirmCancel: 'Avbryta den pågående utskriften? Det går inte att ångra.',
    commandFailed: 'Skrivarkommandot misslyckades. Kontrollera skrivarstatusen och försök igen.',
    commandSent: 'Kommandot för att {action} skickades.',
    commandActions: { pause: 'pausa', resume: 'återuppta' },
    cancelSent: 'Kommandot för att avbryta skickades.',
    unreachable: 'Det gick inte att nå skrivaren. Kontrollera statusen och försök igen.',
    pause: 'Pausa',
    resume: 'Återuppta',
    cancel: 'Avbryt utskrift',
    states: {
      Operational: 'Redo',
      Printing: 'Skriver ut',
      Paused: 'Pausad',
      Offline: 'Offline',
      Closed: 'Frånkopplad',
      Unknown: 'Okänd',
    },
  },
  speed: {
    eyebrow: 'Anslutning',
    title: 'Nätverkshastighet',
    label: 'nätverkshastighet',
    refresh: 'Uppdatera hastighetshistorik',
    latest: 'Senaste testet',
    loading: 'Hämtar hastighetshistorik…',
    loadError: 'Det gick inte att hämta hastighetshistoriken.',
    empty: 'Inga slutförda hastighetstester har registrerats ännu.',
    download: 'Nedladdning',
    upload: 'Uppladdning',
    chartAria: 'Senaste hastighetshistoriken, nedladdning {download}, uppladdning {upload}',
    older: 'Äldre',
    newer: 'Nyare',
  },
  cast: {
    eyebrow: 'Spelas nu',
    title: 'Cast-högtalare',
    refresh: 'Uppdatera Cast-högtalare',
    loadUnavailable: 'Cast-högtalare är inte tillgängliga.',
    invalidDevices: 'Cast-bryggan returnerade en ogiltig enhetslista.',
    loadError: 'Det gick inte att hämta Cast-högtalare.',
    commandFailed: 'Kommandot kunde inte skickas till {device}.',
    commandSent: '{message} för {device}.',
    reachedError: 'Det gick inte att nå Cast-bryggan för {device}.',
    started: 'Uppspelning startad',
    paused: 'Uppspelningen pausad',
    stopped: 'Uppspelningen stoppad',
    volumeUpdated: 'Volymen uppdaterad',
    searching: 'Söker efter Cast-högtalare…',
    bridgeHelp: 'Kontrollera att den lokala Cast-bryggan är igång.',
    empty: 'Inga Cast-högtalare hittades. Enheter visas här när de är tillgängliga i hemnätverket.',
    volume: 'Volym',
    volumeFor: 'Volym för {device}',
    setVolume: 'Ställ in volym',
    commands: { play: 'Spela', pause: 'Pausa', stop: 'Stoppa' },
    sending: 'Skickar…',
  },
  spotify: {
    eyebrow: 'Musik',
    title: 'Spotify',
    refresh: 'Uppdatera Spotify-spelaren',
    loadError: 'Det gick inte att hämta Spotify-uppspelningen.',
    invalidPlayback: 'Spotify returnerade ett ogiltigt uppspelningssvar.',
    invalidDevices: 'Spotify returnerade en ogiltig enhetslista.',
    unavailable: 'Spotify-spelaren är inte tillgänglig.',
    commandFailed: 'Spotify-kommandot misslyckades. Kontrollera anslutningen och försök igen.',
    unreachable: 'Det gick inte att nå Spotify. Kontrollera anslutningen och försök igen.',
    commandMessages: {
      pause: 'Uppspelningen pausades.',
      resume: 'Uppspelningen återupptogs.',
      previous: 'Föregående spår startades.',
      next: 'Nästa spår startades.',
      transfer: 'Uppspelningen flyttades.',
      volume: 'Volymen uppdaterades.',
    },
    profileLoadError: 'Det gick inte att hämta Spotify-profilen.',
    invalidProfile: 'Spotify returnerade ett ogiltigt profilsvar.',
    profileAvailable: 'Profilen är tillgänglig · {name} · {id} · {type}',
    notSet: '(inte angivet)',
    notReturned: '(returnerades inte)',
    profileServiceError: 'Det gick inte att nå Spotifys profiltjänst.',
    loading: 'Hämtar Spotify-spelaren…',
    activeWithoutTrack: 'Uppspelningen är aktiv, men Spotify skickade inga låtuppgifter.',
    nothingPlaying: 'Inget spelas just nu. Starta uppspelning på en Spotify Connect-enhet för att aktivera kontrollerna.',
    episode: 'Podcastavsnitt',
    playing: 'Spelas',
    paused: 'Pausad',
    pause: 'Pausa',
    resume: 'Återuppta',
    played: '{duration} har spelats',
    device: 'Spotify Connect-enhet',
    active: 'Aktiv',
    transfer: 'Flytta uppspelningen',
    volumeFor: 'Volym · {device}',
    volume: 'Volym',
    volumeAria: 'Spotify-volym',
    setVolume: 'Ställ in volym',
    volumeUnsupported: 'Spotify stöder inte fjärrstyrning av volymen på den här enheten. Ändra volymen direkt på enheten.',
    noDevices: 'Inga Spotify Connect-enheter är tillgängliga. Öppna Spotify på en enhet och uppdatera.',
    previous: 'Föregående',
    next: 'Nästa',
    authorize: 'Anslut eller auktorisera Spotify igen',
    testing: 'Testar…',
    testProfile: 'Testa profilen',
    profileNotTested: 'Profiltestet för Spotify har inte körts.',
    authorizationNotConfigured: 'Spotify-auktorisering är inte konfigurerad.',
    authorizationInvalid: 'Spotify-auktoriseringen är ogiltig eller har gått ut.',
    authorizationCanceled: 'Spotify-auktoriseringen avbröts.',
    authorizationResponseInvalid: 'Svaret från Spotify-auktoriseringen är ogiltigt.',
    authorizationStartFailed: 'Det gick inte att starta Spotify-auktoriseringen.',
    authorizationCompleteFailed: 'Det gick inte att slutföra Spotify-auktoriseringen.',
  },
  electrolux: {
    eyebrow: 'Inomhus',
    title: 'Luftkvalitet',
    label: 'Electrolux-luftrenare',
    refresh: 'Uppdatera status för Electrolux-luftrenaren',
    httpError: 'Electrolux-tjänsten svarade med HTTP {status}.',
    invalidStatus: 'Electrolux returnerade ogiltig statusinformation.',
    unreachable: 'Det gick inte att nå den lokala Electrolux-tjänsten.',
    connecting: 'Ansluter till luftrenaren…',
    noMetrics: 'Ansluten, men inga mätvärden kunde hämtas.',
    updateFailed: 'Uppdateringen misslyckades: {error} Visar de senaste mätvärdena.',
    updated: 'Uppdaterad {time}',
  },
  transit: {
    refresh: 'Uppdatera kollektivtrafik',
    requestError: 'Kunde inte hämta avgångarna. Försök igen.',
    invalidResponse: 'Svaret med avgångar var ogiltigt. Försök igen.',
    cancelled: 'Inställd',
    cancelledRelative: 'inställd',
    departingNow: 'avgår nu',
    inMinutes: 'om {minutes} minuter',
    now: 'Nu',
    minutesShort: '{minutes} min',
    line: 'Linje {line}',
    legacyInMinute: 'inom en minut',
    legacyInMinutes: 'om {minutes} min',
    clockAbbreviation: 'kl.',
    noDeparturesShort: 'Inga avgångar',
    towardDeparture: 'Linje {line} mot {destination}, avgår {time}, {relativeTime}',
    noDepartures: 'Inga avgångar tillgängliga.',
    southWest: 'Syd/Väst',
    northEast: 'Nord/Öst',
  },
  electroluxMetrics: {
    pm1: 'PM1.0',
    pm25: 'PM2.5',
    pm10: 'PM10',
    tvoc: 'TVOC',
    temperature: 'Temperatur',
    humidity: 'Luftfuktighet',
    filterLife: 'Filterlivslängd',
    fanSpeed: 'Fläkthastighet',
  },
  switch: {
    submitted: 'Ett namn har skickats.',
    testAlert: 'hej',
    testName: 'hej',
    button: 'iPad-vänlig strömbrytare',
  },
} as const

export function formatCopy(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ''))
}
